name: Version CI

on:
  workflow_dispatch:
  push:
    branches:
      - 'dev/**'

jobs:
  inscrease-version:
    runs-on: ubuntu-latest
    steps:
      - name: Increase patch
        if: "!startsWith(github.event.head_commit.message, '[PATCH]')"
        run: npm version patch
      - name: Increase minor
        if: "!startsWith(github.event.head_commit.message, '[MINOR]')"
        run: npm version minor
      - name: Increase major
        if: "!startsWith(github.event.head_commit.message, '[MAJOR]')"
        run: npm version major    
  build:
    need: 'inscrease-version'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # - name: Print version
    #   run: echo ${{ inscrease-version.outputs. }}
    - name: Login to Docker
      run: docker login -u ${{secrets.DOCKER_USER_NAME}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Deploy to Docker
      run: npm run release